numpy basic

In [1]:
import numpy as np

In [15]:
a=np.array([1,2,3], dtype='int64')
print(a)

[1 2 3]


In [3]:
b=np.array([[1,2,3],[1,2,3]])
print(b)

[[1 2 3]
 [1 2 3]]


In [4]:
#dimension
a.ndim

1

In [5]:
b.ndim

2

In [6]:
a.shape

(3,)

In [7]:
b.shape

(2, 3)

In [9]:
a.dtype

dtype('int64')

In [16]:
a.itemsize

8

In [24]:
a.size

3

In [20]:
#total_size
a.size * a.itemsize

24

In [50]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [51]:
print(a[0, -5])

3


In [52]:
a[0,]

array([1, 2, 3, 4, 5, 6, 7])

In [53]:
a[:]

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [54]:
a[:,2]

array([ 3, 10])

In [55]:
a[0,1:6:2]

array([2, 4, 6])

In [56]:
a[0,4]=20
print(a)

[[ 1  2  3  4 20  6  7]
 [ 8  9 10 11 12 13 14]]


In [57]:
a[:,2]=5
print(a)
a[:,3]=[1,2]
print(a)

[[ 1  2  5  4 20  6  7]
 [ 8  9  5 11 12 13 14]]
[[ 1  2  5  1 20  6  7]
 [ 8  9  5  2 12 13 14]]


In [59]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [61]:
print(b[0,1,1])

4


In [62]:
print(b[1,0,1])

6


In [69]:
print(b[:,:,1])

[[2 4]
 [6 8]]


In [74]:
print(b[:,:,0])

[[1 3]
 [5 7]]


In [84]:
print(b[0,1],b[:,-1,0])

[7 8] [7 7]


In [85]:
b[1,0]

array([5, 6])

In [86]:
b[0,1]=[7,8]
b

array([[[1, 2],
        [7, 8]],

       [[5, 6],
        [7, 8]]])

In [97]:
# zero matrix
np.zeros((5),dtype='int32')

array([0, 0, 0, 0, 0], dtype=int32)

In [101]:
np.zeros((5))

array([0., 0., 0., 0., 0.])

In [111]:
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [117]:
np.ones((4,3,3), dtype='int')

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [121]:
#any number matrix
np.full((2,2,),99)

array([[99, 99],
       [99, 99]])

In [124]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [134]:
np.random.rand(4,2)

array([[0.99309346, 0.4692695 ],
       [0.37524314, 0.32615146],
       [0.23490952, 0.09693464],
       [0.09277358, 0.88677404]])

In [137]:
np.random.random_sample(a.shape)

array([[0.78656947, 0.61728908, 0.57093547, 0.55813598, 0.609619  ,
        0.48290216, 0.15786037],
       [0.93514332, 0.53876422, 0.2007726 , 0.35996472, 0.12986883,
        0.12139191, 0.24879894]])

In [175]:
np.random.randint(-4,7, size=(2,3,3))

array([[[-4,  4, -3],
        [ 0,  3, -3],
        [-3,  6,  0]],

       [[ 2,  3, -2],
        [-1, -4,  2],
        [-1,  4, -1]]], dtype=int32)

In [177]:
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [180]:
arr=np.array([[1,2,3]])
rl=np.repeat(arr,3,axis=0)
print(rl)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [184]:
output=np.ones((5,5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [188]:
z=np.zeros((3,3))
z[1,1]=9
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [199]:
output[1:4,1:4]=z
print(output)

[[0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


math

In [203]:
a=np.array([1,2,3])
b=a.copy()
b[0]=99
print(a,"\n", b)

[1 2 3] 
 [99  2  3]


In [204]:
a+2

array([3, 4, 5])

In [205]:
a-2

array([-1,  0,  1])

In [206]:
a*2

array([2, 4, 6])

In [208]:
a/2

array([0.5, 1. , 1.5])

In [209]:
a%2

array([1, 0, 1])

In [210]:
a**2

array([1, 4, 9])

In [212]:
b=np.array([3,4,5])
a+b

array([4, 6, 8])

In [213]:
a-b

array([-2, -2, -2])

In [214]:
a*b

array([ 3,  8, 15])

In [215]:
a/b

array([0.33333333, 0.5       , 0.6       ])

In [217]:
a%b

array([1, 2, 3])

In [219]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [221]:
np.tan(b)

array([-0.14254654,  1.15782128, -3.38051501])

In [222]:
np.cos(a+b)

array([-0.65364362,  0.96017029, -0.14550003])

In [225]:
a=np.ones((2,3))
b=np.full((3,2),2)
print(a,'\n',b)

[[1. 1. 1.]
 [1. 1. 1.]] 
 [[2 2]
 [2 2]
 [2 2]]


In [227]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [251]:
a=np.random.randint(0,5, size=(3,3))
print(a)
matrix_inverse = np.linalg.inv(a)
print(matrix_inverse)

[[2 4 3]
 [2 4 4]
 [3 1 2]]
[[ 0.4 -0.5  0.4]
 [ 0.8 -0.5 -0.2]
 [-1.   1.  -0. ]]


statistic

In [253]:
stat=np.array([[1,2,3,4],[5,6,7,8]])
stat

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [262]:
np.min((stat),axis=0)

array([1, 2, 3, 4])

In [257]:
print(np.max(stat))

8


In [264]:
print(np.sum(stat))

36


In [275]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)
reshape=arr.reshape((2,2,2))
print(reshape)

(2, 4)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


loading data from a file

In [293]:
file=np.genfromtxt(r"C:\Users\adnan\OneDrive\Desktop\numbers.txt", delimiter=',')
print(file)

[[ 1.  2.  3.  4. 56.  6.  7.  8.  9.]
 [12. 32. 45. 43. 65.  9. 78. 98. 53.]
 [67. 76. 67. 34. 23. 78.  5. 67. 98.]]


In [292]:
filedata=file.astype('int32')
print(filedata)

[[ 1  2  3  4 56  6  7  8  9]
 [12 32 45 43 65  9 78 98 53]
 [67 76 67 34 23 78  5 67 98]]


In [294]:
file>50

array([[False, False, False, False,  True, False, False, False, False],
       [False, False, False, False,  True, False,  True,  True,  True],
       [ True,  True,  True, False, False,  True, False,  True,  True]])

In [295]:
filedata[file>50]

array([56, 65, 78, 98, 53, 67, 76, 67, 78, 67, 98], dtype=int32)

In [297]:
a=np.array([1,2,3,4,5,6,7,8,9])
a[[1,5,7]]

array([2, 6, 8])

In [299]:
np.any([filedata>50],axis=0)

array([[False, False, False, False,  True, False, False, False, False],
       [False, False, False, False,  True, False,  True,  True,  True],
       [ True,  True,  True, False, False,  True, False,  True,  True]])

In [313]:
np.all([filedata>50],axis=1)

array([[False, False, False, False, False, False, False, False, False]])

In [346]:
a=np.random.randint(0,30, size=(6,5))
print(a)

[[23 17 11  3 18]
 [ 6 29 22  0 20]
 [11 22 21 28 18]
 [22  4 23 11 26]
 [ 4  6 16 12  4]
 [ 1 19  9 18 29]]


In [344]:
a[2:4,0:2]

array([[4, 4],
       [6, 4]], dtype=int32)

In [355]:
a[[0,1,2,3],[1,2,3,4]]

array([17, 22, 28, 26], dtype=int32)

In [366]:
a[[0,4,5],3:]

array([[ 3, 18],
       [12,  4],
       [18, 29]], dtype=int32)

In [367]:
a = np.zeros((3,4))
b = np.ones((4,2))
c = np.dot(a, b)
print(c.shape)

(3, 2)


In [380]:
import numpy as np

scores = np.array([45, 78, 92, 55, 88, 63, 71, 84])

# 1. Average score
avg = np.mean(score)

# 2. Highest and lowest
high = np.max(score)
low = np.min(score)

# 3. Count above 70
above_70 = score[score>70]

# 4. Normalise to 0-100
normalised = (score - score.min()) / (score.max() - score.min()) * 100

print(f"Avg: {avg:.1f}, High: {high}, Low: {low}")
print(f"Above 70: {above_70}")
print(f"Normalised: {normalised}")

Avg: 72.0, High: 92, Low: 45
Above 70: [78 92 88 71 84]
Normalised: [  0.          70.21276596 100.          21.27659574  91.4893617
  38.29787234  55.31914894  82.9787234 ]


In [374]:
a = np.arange(1, 6)

In [376]:
a

array([1, 2, 3, 4, 5])

In [377]:
m=a.reshape(5, 1) * a

In [378]:
m

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [379]:
import numpy as np

prices = np.array([100, 102, 98, 105, 110, 107, 115, 112, 118, 120])
window = 3

windows = np.lib.stride_tricks.sliding_window_view(prices, window)
rolling_mean = windows.mean(axis=1)
best_day = np.argmax(rolling_mean) + window - 1
overall_mean = rolling_mean.mean()
hot_days = np.where(rolling_mean > overall_mean)[0] + window - 1

print("Windows shape:", windows.shape)
print("Rolling mean:", rolling_mean.round(2))
print("Best 3-day window ends at index:", best_day)
print("Hot days (indices):", hot_days)

Windows shape: (8, 3)
Rolling mean: [100.   101.67 104.33 107.33 110.67 111.33 115.   116.67]
Best 3-day window ends at index: 9
Hot days (indices): [6 7 8 9]
